### ISSUE TITLE
tempo audio file for compressions activity bpm

### ISSUE THREAD

**Issue by owenm33** [owenm33/drabc-app#13]
The Play button in the CompressionsActivity should trigger a loud metronome sound playing the BPM suggested to use as a guide for compressions frequency (and/or BeeGees 'Staying Alive'). 
Note: this will also involve maybe using the Korg MS-20 mini to create the metronome sound (we could easily download one but that's not as fun)

**Comment by d4vidh4y** [comment]
my first closure
